version: "3"
services:
    # Express 앱 서비스
    app:
        build:
            context: . # Dockerfile이 있는 디렉토리
        expose:
            - ${SERVER_PORT}
        env_file:
            - .env # .env 파일을 사용하여 환경 변수 설정
        networks:
            - appnet

    # Nginx 리버스 프록시 서비스
    nginx:
        image: nginx:latest
        entrypoint: ["/etc/nginx/conf/nginx.conf.generate.sh"]
        ports:
            - "80:80" # 호스트 포트와 컨테이너 포트 매핑
        env_file:
            - .env
        volumes:
            - ./nginx.conf.generate.sh:/etc/nginx/conf/nginx.conf.generate.sh
            - ./nginx.conf.template:/etc/nginx/conf/nginx.conf.template
        depends_on:
            - app
        networks:
            - appnet

networks:
    appnet:
