version: "3"
services:
    # Express 앱 서비스
    app:
        build:
            context: . # Dockerfile이 있는 디렉토리
        expose:
            - 9001
        env_file:
            - .env # .env 파일을 사용하여 환경 변수 설정
        depends_on:
            - nginx
        networks:
            - appnet

    # Nginx 리버스 프록시 서비스
    nginx:
        image: nginx:latest
        ports:
            - "9001:80" # 호스트 포트와 컨테이너 포트 매핑
        env_file:
            - .env
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx 설정 파일
        networks:
            - appnet

networks:
    appnet:
