name: Deploy to Server with WireGuard

on:
    push:
        branches:
            - test

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install and set up WireGuard
              env:
                  WG_CONFIG: ${{ secrets.WG_CONFIG }}
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wireguard
                  echo "$WG_CONFIG" > wg0.conf
                  sudo wg-quick up ./wg0.conf

            - name: Connect to server and deploy
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
              run: |
                  echo "$PRIVATE_KEY" > private_key
                  chmod 600 private_key
                  ssh -i private_key $SERVER_USER@$SERVER_IP "
                    cd ./nginx-deploy-dev
                    git pull
                    docker-compose up -d
                  "
                  rm -f private_key
                  sudo wg-quick down wg0
